/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FSE.view;

/**
 *
 * @author Notandi
 */
public class luggageCustomization extends javax.swing.JDialog {

    /**
     * Creates new form luggageCustomization
     */
    public luggageCustomization(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kgLbsBG = new javax.swing.ButtonGroup();
        carryOnCombo = new javax.swing.JComboBox<>();
        luggageCombo = new javax.swing.JComboBox<>();
        carryOnLabel = new javax.swing.JLabel();
        luggageLabel = new javax.swing.JLabel();
        kilogramsRadio = new javax.swing.JRadioButton();
        poundsRadio = new javax.swing.JRadioButton();
        weightLabel1 = new javax.swing.JLabel();
        weightLabel2 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        carryOnCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "5", "10", "15", "25" }));
        carryOnCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carryOnComboActionPerformed(evt);
            }
        });

        luggageCombo.setMaximumRowCount(9);
        luggageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35" }));
        luggageCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luggageComboActionPerformed(evt);
            }
        });

        carryOnLabel.setText("Carry-on weight");

        luggageLabel.setText("Luggage weight");

        kgLbsBG.add(kilogramsRadio);
        kilogramsRadio.setSelected(true);
        kilogramsRadio.setText("Kilograms");
        kilogramsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilogramsRadioActionPerformed(evt);
            }
        });

        kgLbsBG.add(poundsRadio);
        poundsRadio.setText("Pounds");
        poundsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poundsRadioActionPerformed(evt);
            }
        });

        weightLabel1.setText("kg");

        weightLabel2.setText("kg");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(kilogramsRadio)
                .addGap(18, 18, 18)
                .addComponent(poundsRadio)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carryOnLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(carryOnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luggageLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(luggageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightLabel2)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poundsRadio)
                    .addComponent(kilogramsRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carryOnLabel)
                    .addComponent(luggageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luggageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carryOnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel1)
                    .addComponent(weightLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kilogramsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilogramsRadioActionPerformed
       weightLabel1.setText("kg");
       weightLabel2.setText("kg");
       bookingWindow.bookingWeightLabel.setText("kg");
       
       for(int i = 5; i >= 0; i--){
       carryOnCombo.removeItemAt(i);
       }
       
       carryOnCombo.addItem("0");
       carryOnCombo.addItem("2");
       carryOnCombo.addItem("5");
       carryOnCombo.addItem("10");
       carryOnCombo.addItem("15");
       carryOnCombo.addItem("20");
       
       
       for(int i = 7; i >= 0; i--){
       luggageCombo.removeItemAt(i);
       }
       
       luggageCombo.addItem("0");
       luggageCombo.addItem("5");
       luggageCombo.addItem("10");
       luggageCombo.addItem("15");
       luggageCombo.addItem("20");
       luggageCombo.addItem("25");
       luggageCombo.addItem("30");
       luggageCombo.addItem("35");
       //luggageCombo.addItem("40");
       
    
    }//GEN-LAST:event_kilogramsRadioActionPerformed

    private void poundsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poundsRadioActionPerformed
        weightLabel1.setText("lbs");
        weightLabel2.setText("lbs");
        bookingWindow.bookingWeightLabel.setText("lbs");
        
       for(int i = 5; i >= 0; i--){
       carryOnCombo.removeItemAt(i);
        }
       
       carryOnCombo.addItem("0");
       carryOnCombo.addItem("4,4");
       carryOnCombo.addItem("11");
       carryOnCombo.addItem("22");
       carryOnCombo.addItem("33");
       carryOnCombo.addItem("44");
       
       
       for(int i = 7; i >= 0; i--){
       luggageCombo.removeItemAt(i);
       }
       
       luggageCombo.addItem("0");
       luggageCombo.addItem("11");
       luggageCombo.addItem("22");
       luggageCombo.addItem("33");
       luggageCombo.addItem("44");
       luggageCombo.addItem("55");
       luggageCombo.addItem("66");
       luggageCombo.addItem("77");
      // luggageCombo.addItem("88");
       
    }//GEN-LAST:event_poundsRadioActionPerformed

    private void carryOnComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carryOnComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carryOnComboActionPerformed

    private void luggageComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luggageComboActionPerformed
        
    }//GEN-LAST:event_luggageComboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int a = Integer.parseInt(luggageCombo.getItemAt(luggageCombo.getSelectedIndex())) + 
                Integer.parseInt(carryOnCombo.getItemAt(carryOnCombo.getSelectedIndex()));
        bookingWindow.luggageWeightText.setText(Integer.toString(a));
        
        this.setVisible(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(luggageCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(luggageCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(luggageCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(luggageCustomization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                luggageCustomization dialog = new luggageCustomization(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carryOnCombo;
    private javax.swing.JLabel carryOnLabel;
    private javax.swing.ButtonGroup kgLbsBG;
    private javax.swing.JRadioButton kilogramsRadio;
    private javax.swing.JComboBox<String> luggageCombo;
    private javax.swing.JLabel luggageLabel;
    private javax.swing.JRadioButton poundsRadio;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel weightLabel1;
    private javax.swing.JLabel weightLabel2;
    // End of variables declaration//GEN-END:variables
}
